# Generated by Django 5.1 on 2025-07-26 08:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google')], max_length=8)),
                ('social_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, error_messages={'error': 'This email address is already registered.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Network Account',
                'verbose_name_plural': 'Social Network Accounts',
                'unique_together': {('type', 'social_id')},
            },
        ),
    ]
