// Mocks generated by Mockito 5.4.6 from annotations
// in music_room/test/screens/profile/user_profile_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:music_room/models/api_models.dart' as _i2;
import 'package:music_room/models/music_models.dart' as _i8;
import 'package:music_room/models/sort_models.dart' as _i4;
import 'package:music_room/providers/auth_providers.dart' as _i9;
import 'package:music_room/providers/friend_providers.dart' as _i11;
import 'package:music_room/providers/music_providers.dart' as _i13;
import 'package:music_room/providers/profile_providers.dart' as _i12;
import 'package:music_room/services/api_services.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendsResponse_2 extends _i1.SmartFake
    implements _i2.FriendsResponse {
  _FakeFriendsResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageResponse_3 extends _i1.SmartFake
    implements _i2.MessageResponse {
  _FakeMessageResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendInvitationsResponse_4 extends _i1.SmartFake
    implements _i2.FriendInvitationsResponse {
  _FakeFriendInvitationsResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileByIdResponse_5 extends _i1.SmartFake
    implements _i2.ProfileByIdResponse {
  _FakeProfileByIdResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponse_6 extends _i1.SmartFake
    implements _i2.ProfileResponse {
  _FakeProfileResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeezerSearchResponse_7 extends _i1.SmartFake
    implements _i2.DeezerSearchResponse {
  _FakeDeezerSearchResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistsResponse_8 extends _i1.SmartFake
    implements _i2.PlaylistsResponse {
  _FakePlaylistsResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistDetailResponse_9 extends _i1.SmartFake
    implements _i2.PlaylistDetailResponse {
  _FakePlaylistDetailResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePlaylistResponse_10 extends _i1.SmartFake
    implements _i2.CreatePlaylistResponse {
  _FakeCreatePlaylistResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistLicenseResponse_11 extends _i1.SmartFake
    implements _i2.PlaylistLicenseResponse {
  _FakePlaylistLicenseResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistTracksResponse_12 extends _i1.SmartFake
    implements _i2.PlaylistTracksResponse {
  _FakePlaylistTracksResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoteResponse_13 extends _i1.SmartFake implements _i2.VoteResponse {
  _FakeVoteResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchAddResult_14 extends _i1.SmartFake
    implements _i2.BatchAddResult {
  _FakeBatchAddResult_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignIn_15 extends _i1.SmartFake implements _i3.GoogleSignIn {
  _FakeGoogleSignIn_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrackSortOption_16 extends _i1.SmartFake
    implements _i4.TrackSortOption {
  _FakeTrackSortOption_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddTrackResult_17 extends _i1.SmartFake
    implements _i2.AddTrackResult {
  _FakeAddTrackResult_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i7.Future<_i2.AuthResult> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i7.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> logout(String? token, _i2.LogoutRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.AuthResult> facebookLogin(_i2.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, [request]),
            returnValue: _i7.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#facebookLogin, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<_i2.AuthResult> googleLogin(_i2.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [request]),
            returnValue: _i7.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#googleLogin, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> forgotPassword(_i2.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> forgotChangePassword(_i2.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotChangePassword, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendSignupEmailOtp(_i2.EmailOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.AuthResult> signupWithOtp(_i2.SignupWithOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [request]),
            returnValue: _i7.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#signupWithOtp, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> facebookLink(
    String? token,
    _i2.SocialLinkRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLink, [token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> googleLink(String? token, _i2.SocialLinkRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLink, [token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserResponse> getUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [token]),
            returnValue: _i7.Future<_i2.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getUser, [token])),
            ),
          )
          as _i7.Future<_i2.UserResponse>);

  @override
  _i7.Future<void> userPasswordChange(
    String? token,
    _i2.PasswordChangeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#userPasswordChange, [token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.FriendsResponse> getFriends(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, [token]),
            returnValue: _i7.Future<_i2.FriendsResponse>.value(
              _FakeFriendsResponse_2(
                this,
                Invocation.method(#getFriends, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.FriendsResponse>);

  @override
  _i7.Future<_i2.MessageResponse> sendFriendRequest(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [userId, token]),
            returnValue: _i7.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_3(
                this,
                Invocation.method(#sendFriendRequest, [userId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.MessageResponse>);

  @override
  _i7.Future<_i2.MessageResponse> acceptFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendRequest, [friendshipId, token]),
            returnValue: _i7.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_3(
                this,
                Invocation.method(#acceptFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.MessageResponse>);

  @override
  _i7.Future<_i2.MessageResponse> rejectFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectFriendRequest, [friendshipId, token]),
            returnValue: _i7.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_3(
                this,
                Invocation.method(#rejectFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.MessageResponse>);

  @override
  _i7.Future<void> removeFriend(String? userId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [userId, token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> logActivity(
    String? token,
    _i2.ActivityLogRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logActivity, [token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.FriendInvitationsResponse> getReceivedInvitations(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReceivedInvitations, [token]),
            returnValue: _i7.Future<_i2.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_4(
                this,
                Invocation.method(#getReceivedInvitations, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.FriendInvitationsResponse>);

  @override
  _i7.Future<_i2.FriendInvitationsResponse> getSentInvitations(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSentInvitations, [token]),
            returnValue: _i7.Future<_i2.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_4(
                this,
                Invocation.method(#getSentInvitations, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.FriendInvitationsResponse>);

  @override
  _i7.Future<Map<String, dynamic>> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.ProfileByIdResponse> getProfileById(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [userId, token]),
            returnValue: _i7.Future<_i2.ProfileByIdResponse>.value(
              _FakeProfileByIdResponse_5(
                this,
                Invocation.method(#getProfileById, [userId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.ProfileByIdResponse>);

  @override
  _i7.Future<_i2.ProfileResponse> getMyProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, [token]),
            returnValue: _i7.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_6(
                this,
                Invocation.method(#getMyProfile, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.ProfileResponse>);

  @override
  _i7.Future<void> updateProfile(String? token, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [token, data]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.ProfileResponse> updateProfileFull(
    String? token,
    _i2.ProfileUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileFull, [token, request]),
            returnValue: _i7.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_6(
                this,
                Invocation.method(#updateProfileFull, [token, request]),
              ),
            ),
          )
          as _i7.Future<_i2.ProfileResponse>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getMusicPreferences(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMusicPreferences, [token]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> deleteAvatar(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.ProfileResponse> updateProfileWithFile(
    String? token, {
    String? avatarPath,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFile,
              [token],
              {
                #avatarPath: avatarPath,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i7.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_6(
                this,
                Invocation.method(
                  #updateProfileWithFile,
                  [token],
                  {
                    #avatarPath: avatarPath,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ProfileResponse>);

  @override
  _i7.Future<_i2.ProfileResponse> updateProfileWithFileWeb(
    String? token, {
    List<int>? avatarBytes,
    String? mimeType,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFileWeb,
              [token],
              {
                #avatarBytes: avatarBytes,
                #mimeType: mimeType,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i7.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_6(
                this,
                Invocation.method(
                  #updateProfileWithFileWeb,
                  [token],
                  {
                    #avatarBytes: avatarBytes,
                    #mimeType: mimeType,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.ProfileResponse>);

  @override
  _i7.Future<_i2.DeezerSearchResponse> searchDeezerTracks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDeezerTracks, [query]),
            returnValue: _i7.Future<_i2.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_7(
                this,
                Invocation.method(#searchDeezerTracks, [query]),
              ),
            ),
          )
          as _i7.Future<_i2.DeezerSearchResponse>);

  @override
  _i7.Future<_i2.DeezerSearchResponse> searchTracks(
    String? query,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query, token]),
            returnValue: _i7.Future<_i2.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_7(
                this,
                Invocation.method(#searchTracks, [query, token]),
              ),
            ),
          )
          as _i7.Future<_i2.DeezerSearchResponse>);

  @override
  _i7.Future<_i8.Track?> getDeezerTrack(String? trackId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getDeezerTrack, [trackId, token]),
            returnValue: _i7.Future<_i8.Track?>.value(),
          )
          as _i7.Future<_i8.Track?>);

  @override
  _i7.Future<Map<String, dynamic>> addTrackFromDeezer(
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackFromDeezer, [trackId, token]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.PlaylistsResponse> getSavedPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPlaylists, [token]),
            returnValue: _i7.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_8(
                this,
                Invocation.method(#getSavedPlaylists, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistsResponse>);

  @override
  _i7.Future<_i2.PlaylistsResponse> getPublicPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicPlaylists, [token]),
            returnValue: _i7.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_8(
                this,
                Invocation.method(#getPublicPlaylists, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistsResponse>);

  @override
  _i7.Future<_i2.PlaylistDetailResponse> getPlaylist(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [id, token]),
            returnValue: _i7.Future<_i2.PlaylistDetailResponse>.value(
              _FakePlaylistDetailResponse_9(
                this,
                Invocation.method(#getPlaylist, [id, token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistDetailResponse>);

  @override
  _i7.Future<_i2.CreatePlaylistResponse> createPlaylist(
    String? token,
    _i2.CreatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [token, request]),
            returnValue: _i7.Future<_i2.CreatePlaylistResponse>.value(
              _FakeCreatePlaylistResponse_10(
                this,
                Invocation.method(#createPlaylist, [token, request]),
              ),
            ),
          )
          as _i7.Future<_i2.CreatePlaylistResponse>);

  @override
  _i7.Future<void> updatePlaylist(
    String? playlistId,
    String? token,
    _i2.UpdatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlistId, token, request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> changePlaylistVisibility(
    String? playlistId,
    String? token,
    _i2.VisibilityRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePlaylistVisibility, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> inviteUserToPlaylist(
    String? playlistId,
    String? token,
    _i2.InviteUserRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inviteUserToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.PlaylistLicenseResponse> getPlaylistLicense(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistLicense, [playlistId, token]),
            returnValue: _i7.Future<_i2.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_11(
                this,
                Invocation.method(#getPlaylistLicense, [playlistId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistLicenseResponse>);

  @override
  _i7.Future<_i2.PlaylistLicenseResponse> updatePlaylistLicense(
    String? playlistId,
    String? token,
    _i2.PlaylistLicenseRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylistLicense, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i7.Future<_i2.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_11(
                this,
                Invocation.method(#updatePlaylistLicense, [
                  playlistId,
                  token,
                  request,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistLicenseResponse>);

  @override
  _i7.Future<_i2.PlaylistTracksResponse> getPlaylistTracks(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTracks, [playlistId, token]),
            returnValue: _i7.Future<_i2.PlaylistTracksResponse>.value(
              _FakePlaylistTracksResponse_12(
                this,
                Invocation.method(#getPlaylistTracks, [playlistId, token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistTracksResponse>);

  @override
  _i7.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? token,
    _i2.AddTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [
              playlistId,
              trackId,
              token,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> moveTrackInPlaylist(
    String? playlistId,
    String? token,
    _i2.MoveTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveTrackInPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deletePlaylist(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId, token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.PlaylistsResponse> getSavedEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedEvents, [token]),
            returnValue: _i7.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_8(
                this,
                Invocation.method(#getSavedEvents, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistsResponse>);

  @override
  _i7.Future<_i2.PlaylistsResponse> getPublicEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicEvents, [token]),
            returnValue: _i7.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_8(
                this,
                Invocation.method(#getPublicEvents, [token]),
              ),
            ),
          )
          as _i7.Future<_i2.PlaylistsResponse>);

  @override
  _i7.Future<_i2.VoteResponse> voteForTrack(
    String? playlistId,
    String? token,
    _i2.VoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteForTrack, [playlistId, token, request]),
            returnValue: _i7.Future<_i2.VoteResponse>.value(
              _FakeVoteResponse_13(
                this,
                Invocation.method(#voteForTrack, [playlistId, token, request]),
              ),
            ),
          )
          as _i7.Future<_i2.VoteResponse>);

  @override
  _i7.Future<_i2.BatchAddResult> addMultipleTracksToPlaylist({
    required String? playlistId,
    required List<String>? trackIds,
    required String? token,
    String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleTracksToPlaylist, [], {
              #playlistId: playlistId,
              #trackIds: trackIds,
              #token: token,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i7.Future<_i2.BatchAddResult>.value(
              _FakeBatchAddResult_14(
                this,
                Invocation.method(#addMultipleTracksToPlaylist, [], {
                  #playlistId: playlistId,
                  #trackIds: trackIds,
                  #token: token,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.BatchAddResult>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getRandomTracks({int? count = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomTracks, [], {#count: count}),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get hasValidToken =>
      (super.noSuchMethod(Invocation.getter(#hasValidToken), returnValue: false)
          as bool);

  @override
  _i3.GoogleSignIn get googleSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignIn),
            returnValue: _FakeGoogleSignIn_15(
              this,
              Invocation.getter(#googleSignIn),
            ),
          )
          as _i3.GoogleSignIn);

  @override
  Map<String, String> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> resetPasswordWithOtp(
    String? email,
    String? otp,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordWithOtp, [email, otp, newPassword]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendSignupEmailOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [email]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> signupWithOtp(
    String? username,
    String? email,
    String? password,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [username, email, password, otp]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> googleLogin() =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> handleWebGoogleSignIn(_i3.GoogleSignInAccount? user) =>
      (super.noSuchMethod(
            Invocation.method(#handleWebGoogleSignIn, [user]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> facebookLogin() =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> checkEmailAvailability(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailability, [email]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<T?> executeAsync<T>(
    _i7.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<T?>.value(),
          )
          as _i7.Future<T?>);

  @override
  _i7.Future<bool> executeBool(
    _i7.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FriendProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendProvider extends _i1.Mock implements _i11.FriendProvider {
  MockFriendProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Friend> get friends =>
      (super.noSuchMethod(
            Invocation.getter(#friends),
            returnValue: <_i2.Friend>[],
          )
          as List<_i2.Friend>);

  @override
  List<Map<String, dynamic>> get receivedInvitations =>
      (super.noSuchMethod(
            Invocation.getter(#receivedInvitations),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get sentInvitations =>
      (super.noSuchMethod(
            Invocation.getter(#sentInvitations),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchFriends(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFriends, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchReceivedInvitations(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchReceivedInvitations, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchSentInvitations(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSentInvitations, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> sendFriendRequest(String? token, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [token, userId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> acceptFriendRequest(String? token, String? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendRequest, [token, friendshipId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> rejectFriendRequest(String? token, String? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectFriendRequest, [token, friendshipId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> removeFriend(String? token, String? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [token, friendId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void clearFriends() => super.noSuchMethod(
    Invocation.method(#clearFriends, []),
    returnValueForMissingStub: null,
  );

  @override
  String? getFriendshipId(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getFriendshipId, [invitation]))
          as String?);

  @override
  String? getFromUserId(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getFromUserId, [invitation]))
          as String?);

  @override
  String? getToUserId(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getToUserId, [invitation]))
          as String?);

  @override
  String? getInvitationStatus(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getInvitationStatus, [invitation]))
          as String?);

  @override
  String? getFromUsername(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getFromUsername, [invitation]))
          as String?);

  @override
  String? getToUsername(Map<String, dynamic>? invitation) =>
      (super.noSuchMethod(Invocation.method(#getToUsername, [invitation]))
          as String?);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<T?> executeAsync<T>(
    _i7.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<T?>.value(),
          )
          as _i7.Future<T?>);

  @override
  _i7.Future<bool> executeBool(
    _i7.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileProvider extends _i1.Mock implements _i12.ProfileProvider {
  MockProfileProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GoogleSignIn get googleSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignIn),
            returnValue: _FakeGoogleSignIn_15(
              this,
              Invocation.getter(#googleSignIn),
            ),
          )
          as _i3.GoogleSignIn);

  @override
  bool get isPasswordUsable =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUsable),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void resetValues() => super.noSuchMethod(
    Invocation.method(#resetValues, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> loadProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#loadProfile, [token]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> userPasswordChange(
    String? token,
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#userPasswordChange, [
              token,
              currentPassword,
              newPassword,
            ]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> facebookLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLink, [token]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> googleLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#googleLink, [token]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> updateProfile(
    String? token, {
    String? avatarBase64,
    String? mimeType,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    List<Map<String, dynamic>>? availableMusicPreferences,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfile,
              [token],
              {
                #avatarBase64: avatarBase64,
                #mimeType: mimeType,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #availableMusicPreferences: availableMusicPreferences,
              },
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> updateVisibility(
    String? token, {
    _i12.VisibilityLevel? avatarVisibility,
    _i12.VisibilityLevel? nameVisibility,
    _i12.VisibilityLevel? locationVisibility,
    _i12.VisibilityLevel? bioVisibility,
    _i12.VisibilityLevel? phoneVisibility,
    _i12.VisibilityLevel? friendInfoVisibility,
    _i12.VisibilityLevel? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateVisibility,
              [token],
              {
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getMusicPreferences(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMusicPreferences, [token]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<bool> deleteAvatar(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, [token]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<T?> executeAsync<T>(
    _i7.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<T?>.value(),
          )
          as _i7.Future<T?>);

  @override
  _i7.Future<bool> executeBool(
    _i7.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MusicProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicProvider extends _i1.Mock implements _i13.MusicProvider {
  MockMusicProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Playlist> get playlists =>
      (super.noSuchMethod(
            Invocation.getter(#playlists),
            returnValue: <_i8.Playlist>[],
          )
          as List<_i8.Playlist>);

  @override
  List<_i8.Playlist> get userPlaylists =>
      (super.noSuchMethod(
            Invocation.getter(#userPlaylists),
            returnValue: <_i8.Playlist>[],
          )
          as List<_i8.Playlist>);

  @override
  List<_i8.Playlist> get publicPlaylists =>
      (super.noSuchMethod(
            Invocation.getter(#publicPlaylists),
            returnValue: <_i8.Playlist>[],
          )
          as List<_i8.Playlist>);

  @override
  List<_i8.Track> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i8.Track>[],
          )
          as List<_i8.Track>);

  @override
  List<_i8.PlaylistTrack> get playlistTracks =>
      (super.noSuchMethod(
            Invocation.getter(#playlistTracks),
            returnValue: <_i8.PlaylistTrack>[],
          )
          as List<_i8.PlaylistTrack>);

  @override
  bool get hasConnectionError =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnectionError),
            returnValue: false,
          )
          as bool);

  @override
  _i4.TrackSortOption get currentSortOption =>
      (super.noSuchMethod(
            Invocation.getter(#currentSortOption),
            returnValue: _FakeTrackSortOption_16(
              this,
              Invocation.getter(#currentSortOption),
            ),
          )
          as _i4.TrackSortOption);

  @override
  List<_i8.PlaylistTrack> get sortedPlaylistTracks =>
      (super.noSuchMethod(
            Invocation.getter(#sortedPlaylistTracks),
            returnValue: <_i8.PlaylistTrack>[],
          )
          as List<_i8.PlaylistTrack>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSortOption(_i4.TrackSortOption? sortOption) => super.noSuchMethod(
    Invocation.method(#setSortOption, [sortOption]),
    returnValueForMissingStub: null,
  );

  @override
  void resetToCustomOrder() => super.noSuchMethod(
    Invocation.method(#resetToCustomOrder, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> fetchUserPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserPlaylists, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchPublicPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPublicPlaylists, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchAllPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllPlaylists, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i8.Playlist?> getPlaylistDetails(String? id, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistDetails, [id, token]),
            returnValue: _i7.Future<_i8.Playlist?>.value(),
          )
          as _i7.Future<_i8.Playlist?>);

  @override
  _i7.Future<String?> createPlaylist(
    String? name,
    String? description,
    bool? isPublic,
    String? token,
    String? licenseType,
    bool? isEvent, [
    String? deviceUuid,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [
              name,
              description,
              isPublic,
              token,
              licenseType,
              isEvent,
              deviceUuid,
            ]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> searchDeezerTracks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDeezerTracks, [query]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i8.Track?> getDeezerTrack(String? trackId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getDeezerTrack, [trackId, token]),
            returnValue: _i7.Future<_i8.Track?>.value(),
          )
          as _i7.Future<_i8.Track?>);

  @override
  _i8.Track? getTrackById(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#getTrackById, [trackId]))
          as _i8.Track?);

  @override
  _i7.Future<void> fetchPlaylistTracks(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlaylistTracks, [playlistId, token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setPlaylistTracks(List<_i8.PlaylistTrack>? tracks) => super.noSuchMethod(
    Invocation.method(#setPlaylistTracks, [tracks]),
    returnValueForMissingStub: null,
  );

  @override
  bool isTrackInPlaylist(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrackInPlaylist, [trackId]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<_i2.AddTrackResult> addTrackToPlaylist(
    String? playlistId,
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [
              playlistId,
              trackId,
              token,
            ]),
            returnValue: _i7.Future<_i2.AddTrackResult>.value(
              _FakeAddTrackResult_17(
                this,
                Invocation.method(#addTrackToPlaylist, [
                  playlistId,
                  trackId,
                  token,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.AddTrackResult>);

  @override
  _i7.Future<_i2.AddTrackResult> addTrackObjectToPlaylist(
    String? playlistId,
    _i8.Track? track,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackObjectToPlaylist, [
              playlistId,
              track,
              token,
            ]),
            returnValue: _i7.Future<_i2.AddTrackResult>.value(
              _FakeAddTrackResult_17(
                this,
                Invocation.method(#addTrackObjectToPlaylist, [
                  playlistId,
                  track,
                  token,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.AddTrackResult>);

  @override
  _i7.Future<_i2.AddTrackResult> addRandomTrackToPlaylist(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRandomTrackToPlaylist, [playlistId, token]),
            returnValue: _i7.Future<_i2.AddTrackResult>.value(
              _FakeAddTrackResult_17(
                this,
                Invocation.method(#addRandomTrackToPlaylist, [
                  playlistId,
                  token,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.AddTrackResult>);

  @override
  _i7.Future<_i2.BatchAddResult> addMultipleTracksToPlaylist({
    required String? playlistId,
    required List<String>? trackIds,
    required String? token,
    String? deviceUuid,
    dynamic Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleTracksToPlaylist, [], {
              #playlistId: playlistId,
              #trackIds: trackIds,
              #token: token,
              #deviceUuid: deviceUuid,
              #onProgress: onProgress,
            }),
            returnValue: _i7.Future<_i2.BatchAddResult>.value(
              _FakeBatchAddResult_14(
                this,
                Invocation.method(#addMultipleTracksToPlaylist, [], {
                  #playlistId: playlistId,
                  #trackIds: trackIds,
                  #token: token,
                  #deviceUuid: deviceUuid,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.BatchAddResult>);

  @override
  _i7.Future<void> removeTrackFromPlaylist({
    required String? playlistId,
    required String? trackId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [], {
              #playlistId: playlistId,
              #trackId: trackId,
              #token: token,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> moveTrackInPlaylist({
    required String? playlistId,
    required int? rangeStart,
    required int? insertBefore,
    required String? token,
    int? rangeLength = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveTrackInPlaylist, [], {
              #playlistId: playlistId,
              #rangeStart: rangeStart,
              #insertBefore: insertBefore,
              #token: token,
              #rangeLength: rangeLength,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void updateTrackInPlaylist(String? trackId, _i8.Track? trackDetails) =>
      super.noSuchMethod(
        Invocation.method(#updateTrackInPlaylist, [trackId, trackDetails]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePlaylistTracks(List<_i8.PlaylistTrack>? updatedTracks) =>
      super.noSuchMethod(
        Invocation.method(#updatePlaylistTracks, [updatedTracks]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePlaylistTracksWithPreload(
    List<_i8.PlaylistTrack>? updatedTracks,
  ) => super.noSuchMethod(
    Invocation.method(#updatePlaylistTracksWithPreload, [updatedTracks]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePlaylistInCache(
    String? playlistId, {
    String? name,
    String? description,
    bool? isPublic,
    List<_i8.Track>? tracks,
    String? licenseType,
    bool? isEvent,
    List<_i8.User>? sharedWith,
  }) => super.noSuchMethod(
    Invocation.method(
      #updatePlaylistInCache,
      [playlistId],
      {
        #name: name,
        #description: description,
        #isPublic: isPublic,
        #tracks: tracks,
        #licenseType: licenseType,
        #isEvent: isEvent,
        #sharedWith: sharedWith,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> updatePlaylistDetails(
    String? playlistId,
    String? token, {
    String? name,
    String? description,
    bool? isEvent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePlaylistDetails,
              [playlistId, token],
              {#name: name, #description: description, #isEvent: isEvent},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> shufflePlaylistTracks(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#shufflePlaylistTracks, [playlistId, token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> forceRefreshPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshPlaylists, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> deletePlaylist(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId, token]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i8.Playlist>> getSavedEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedEvents, [token]),
            returnValue: _i7.Future<List<_i8.Playlist>>.value(<_i8.Playlist>[]),
          )
          as _i7.Future<List<_i8.Playlist>>);

  @override
  _i7.Future<List<_i8.Playlist>> getPublicEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicEvents, [token]),
            returnValue: _i7.Future<List<_i8.Playlist>>.value(<_i8.Playlist>[]),
          )
          as _i7.Future<List<_i8.Playlist>>);

  @override
  _i7.Future<List<_i8.Track>> getRandomTracksFromAPI({int? count = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomTracksFromAPI, [], {#count: count}),
            returnValue: _i7.Future<List<_i8.Track>>.value(<_i8.Track>[]),
          )
          as _i7.Future<List<_i8.Track>>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<T?> executeAsync<T>(
    _i7.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<T?>.value(),
          )
          as _i7.Future<T?>);

  @override
  _i7.Future<bool> executeBool(
    _i7.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
