// Mocks generated by Mockito 5.4.6 from annotations
// in music_room/test/screens/auth/auth_screens_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:music_room/providers/auth_providers.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleSignIn_0 extends _i1.SmartFake implements _i2.GoogleSignIn {
  _FakeGoogleSignIn_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get hasValidToken =>
      (super.noSuchMethod(Invocation.getter(#hasValidToken), returnValue: false)
          as bool);

  @override
  _i2.GoogleSignIn get googleSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignIn),
            returnValue: _FakeGoogleSignIn_0(
              this,
              Invocation.getter(#googleSignIn),
            ),
          )
          as _i2.GoogleSignIn);

  @override
  Map<String, String> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resetPasswordWithOtp(
    String? email,
    String? otp,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordWithOtp, [email, otp, newPassword]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> sendSignupEmailOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> signupWithOtp(
    String? username,
    String? email,
    String? password,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [username, email, password, otp]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> googleLogin() =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> handleWebGoogleSignIn(_i2.GoogleSignInAccount? user) =>
      (super.noSuchMethod(
            Invocation.method(#handleWebGoogleSignIn, [user]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> facebookLogin() =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkEmailAvailability(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailability, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<T?> executeAsync<T>(
    _i4.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<bool> executeBool(
    _i4.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
