# Generated by Django 5.1 on 2025-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='picture_medium',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='picture_small',
            field=models.URLField(default=''),
        ),
    ]
