# Generated by Django 5.1 on 2025-07-30 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('location_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('bio_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='private', max_length=10)),
                ('friend_info', models.TextField(blank=True)),
                ('friend_info_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='friends', max_length=10)),
                ('music_preferences_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10)),
                ('music_preferences', models.ManyToManyField(blank=True, to='profile.musicpreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
