// Mocks generated by Mockito 5.4.6 from annotations
// in music_room/test/providers/auth_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i12;

import 'package:google_sign_in/google_sign_in.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:music_room/models/api_models.dart' as _i3;
import 'package:music_room/models/music_models.dart' as _i8;
import 'package:music_room/providers/theme_providers.dart' as _i4;
import 'package:music_room/services/api_services.dart' as _i2;
import 'package:music_room/services/auth_services.dart' as _i5;
import 'package:music_room/services/logging_services.dart' as _i10;
import 'package:music_room/services/player_services.dart' as _i11;
import 'package:music_room/services/websocket_services.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_2 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendsResponse_3 extends _i1.SmartFake
    implements _i3.FriendsResponse {
  _FakeFriendsResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageResponse_4 extends _i1.SmartFake
    implements _i3.MessageResponse {
  _FakeMessageResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendInvitationsResponse_5 extends _i1.SmartFake
    implements _i3.FriendInvitationsResponse {
  _FakeFriendInvitationsResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileByIdResponse_6 extends _i1.SmartFake
    implements _i3.ProfileByIdResponse {
  _FakeProfileByIdResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponse_7 extends _i1.SmartFake
    implements _i3.ProfileResponse {
  _FakeProfileResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeezerSearchResponse_8 extends _i1.SmartFake
    implements _i3.DeezerSearchResponse {
  _FakeDeezerSearchResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistsResponse_9 extends _i1.SmartFake
    implements _i3.PlaylistsResponse {
  _FakePlaylistsResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistDetailResponse_10 extends _i1.SmartFake
    implements _i3.PlaylistDetailResponse {
  _FakePlaylistDetailResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePlaylistResponse_11 extends _i1.SmartFake
    implements _i3.CreatePlaylistResponse {
  _FakeCreatePlaylistResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistLicenseResponse_12 extends _i1.SmartFake
    implements _i3.PlaylistLicenseResponse {
  _FakePlaylistLicenseResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistTracksResponse_13 extends _i1.SmartFake
    implements _i3.PlaylistTracksResponse {
  _FakePlaylistTracksResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoteResponse_14 extends _i1.SmartFake implements _i3.VoteResponse {
  _FakeVoteResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchAddResult_15 extends _i1.SmartFake
    implements _i3.BatchAddResult {
  _FakeBatchAddResult_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDynamicThemeProvider_16 extends _i1.SmartFake
    implements _i4.DynamicThemeProvider {
  _FakeDynamicThemeProvider_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_17 extends _i1.SmartFake implements Duration {
  _FakeDuration_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i2.ApiService get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiService_0(this, Invocation.getter(#api)),
          )
          as _i2.ApiService);

  @override
  _i6.Future<_i3.AuthResult> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> facebookLogin(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, [accessToken]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#facebookLogin, [accessToken]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> googleLogin({
    String? idToken,
    String? socialId,
    String? socialEmail,
    String? socialName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [], {
              #idToken: idToken,
              #socialId: socialId,
              #socialEmail: socialEmail,
              #socialName: socialName,
            }),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#googleLogin, [], {
                  #idToken: idToken,
                  #socialId: socialId,
                  #socialEmail: socialEmail,
                  #socialName: socialName,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> sendSignupEmailOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> signupWithOtp(
    String? username,
    String? email,
    String? password,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [username, email, password, otp]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#signupWithOtp, [
                  username,
                  email,
                  password,
                  otp,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<_i3.AuthResult> login(_i3.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> logout(String? token, _i3.LogoutRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> facebookLogin(_i3.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, [request]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#facebookLogin, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> googleLogin(_i3.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [request]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#googleLogin, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> forgotPassword(_i3.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forgotChangePassword(_i3.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotChangePassword, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendSignupEmailOtp(_i3.EmailOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> signupWithOtp(_i3.SignupWithOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [request]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#signupWithOtp, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> facebookLink(
    String? token,
    _i3.SocialLinkRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLink, [token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> googleLink(String? token, _i3.SocialLinkRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLink, [token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserResponse> getUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [token]),
            returnValue: _i6.Future<_i3.UserResponse>.value(
              _FakeUserResponse_2(this, Invocation.method(#getUser, [token])),
            ),
          )
          as _i6.Future<_i3.UserResponse>);

  @override
  _i6.Future<void> userPasswordChange(
    String? token,
    _i3.PasswordChangeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#userPasswordChange, [token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.FriendsResponse> getFriends(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, [token]),
            returnValue: _i6.Future<_i3.FriendsResponse>.value(
              _FakeFriendsResponse_3(
                this,
                Invocation.method(#getFriends, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.FriendsResponse>);

  @override
  _i6.Future<_i3.MessageResponse> sendFriendRequest(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [userId, token]),
            returnValue: _i6.Future<_i3.MessageResponse>.value(
              _FakeMessageResponse_4(
                this,
                Invocation.method(#sendFriendRequest, [userId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.MessageResponse>);

  @override
  _i6.Future<_i3.MessageResponse> acceptFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendRequest, [friendshipId, token]),
            returnValue: _i6.Future<_i3.MessageResponse>.value(
              _FakeMessageResponse_4(
                this,
                Invocation.method(#acceptFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.MessageResponse>);

  @override
  _i6.Future<_i3.MessageResponse> rejectFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectFriendRequest, [friendshipId, token]),
            returnValue: _i6.Future<_i3.MessageResponse>.value(
              _FakeMessageResponse_4(
                this,
                Invocation.method(#rejectFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.MessageResponse>);

  @override
  _i6.Future<void> removeFriend(String? userId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [userId, token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logActivity(
    String? token,
    _i3.ActivityLogRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logActivity, [token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.FriendInvitationsResponse> getReceivedInvitations(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReceivedInvitations, [token]),
            returnValue: _i6.Future<_i3.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_5(
                this,
                Invocation.method(#getReceivedInvitations, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.FriendInvitationsResponse>);

  @override
  _i6.Future<_i3.FriendInvitationsResponse> getSentInvitations(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSentInvitations, [token]),
            returnValue: _i6.Future<_i3.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_5(
                this,
                Invocation.method(#getSentInvitations, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.FriendInvitationsResponse>);

  @override
  _i6.Future<Map<String, dynamic>> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.ProfileByIdResponse> getProfileById(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [userId, token]),
            returnValue: _i6.Future<_i3.ProfileByIdResponse>.value(
              _FakeProfileByIdResponse_6(
                this,
                Invocation.method(#getProfileById, [userId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.ProfileByIdResponse>);

  @override
  _i6.Future<_i3.ProfileResponse> getMyProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, [token]),
            returnValue: _i6.Future<_i3.ProfileResponse>.value(
              _FakeProfileResponse_7(
                this,
                Invocation.method(#getMyProfile, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.ProfileResponse>);

  @override
  _i6.Future<void> updateProfile(String? token, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [token, data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ProfileResponse> updateProfileFull(
    String? token,
    _i3.ProfileUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileFull, [token, request]),
            returnValue: _i6.Future<_i3.ProfileResponse>.value(
              _FakeProfileResponse_7(
                this,
                Invocation.method(#updateProfileFull, [token, request]),
              ),
            ),
          )
          as _i6.Future<_i3.ProfileResponse>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMusicPreferences(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMusicPreferences, [token]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> deleteAvatar(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ProfileResponse> updateProfileWithFile(
    String? token, {
    String? avatarPath,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFile,
              [token],
              {
                #avatarPath: avatarPath,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i6.Future<_i3.ProfileResponse>.value(
              _FakeProfileResponse_7(
                this,
                Invocation.method(
                  #updateProfileWithFile,
                  [token],
                  {
                    #avatarPath: avatarPath,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.ProfileResponse>);

  @override
  _i6.Future<_i3.ProfileResponse> updateProfileWithFileWeb(
    String? token, {
    List<int>? avatarBytes,
    String? mimeType,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFileWeb,
              [token],
              {
                #avatarBytes: avatarBytes,
                #mimeType: mimeType,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i6.Future<_i3.ProfileResponse>.value(
              _FakeProfileResponse_7(
                this,
                Invocation.method(
                  #updateProfileWithFileWeb,
                  [token],
                  {
                    #avatarBytes: avatarBytes,
                    #mimeType: mimeType,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.ProfileResponse>);

  @override
  _i6.Future<_i3.DeezerSearchResponse> searchDeezerTracks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDeezerTracks, [query]),
            returnValue: _i6.Future<_i3.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_8(
                this,
                Invocation.method(#searchDeezerTracks, [query]),
              ),
            ),
          )
          as _i6.Future<_i3.DeezerSearchResponse>);

  @override
  _i6.Future<_i3.DeezerSearchResponse> searchTracks(
    String? query,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query, token]),
            returnValue: _i6.Future<_i3.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_8(
                this,
                Invocation.method(#searchTracks, [query, token]),
              ),
            ),
          )
          as _i6.Future<_i3.DeezerSearchResponse>);

  @override
  _i6.Future<_i8.Track?> getDeezerTrack(String? trackId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getDeezerTrack, [trackId, token]),
            returnValue: _i6.Future<_i8.Track?>.value(),
          )
          as _i6.Future<_i8.Track?>);

  @override
  _i6.Future<Map<String, dynamic>> addTrackFromDeezer(
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackFromDeezer, [trackId, token]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.PlaylistsResponse> getSavedPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPlaylists, [token]),
            returnValue: _i6.Future<_i3.PlaylistsResponse>.value(
              _FakePlaylistsResponse_9(
                this,
                Invocation.method(#getSavedPlaylists, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistsResponse>);

  @override
  _i6.Future<_i3.PlaylistsResponse> getPublicPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicPlaylists, [token]),
            returnValue: _i6.Future<_i3.PlaylistsResponse>.value(
              _FakePlaylistsResponse_9(
                this,
                Invocation.method(#getPublicPlaylists, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistsResponse>);

  @override
  _i6.Future<_i3.PlaylistDetailResponse> getPlaylist(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [id, token]),
            returnValue: _i6.Future<_i3.PlaylistDetailResponse>.value(
              _FakePlaylistDetailResponse_10(
                this,
                Invocation.method(#getPlaylist, [id, token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistDetailResponse>);

  @override
  _i6.Future<_i3.CreatePlaylistResponse> createPlaylist(
    String? token,
    _i3.CreatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [token, request]),
            returnValue: _i6.Future<_i3.CreatePlaylistResponse>.value(
              _FakeCreatePlaylistResponse_11(
                this,
                Invocation.method(#createPlaylist, [token, request]),
              ),
            ),
          )
          as _i6.Future<_i3.CreatePlaylistResponse>);

  @override
  _i6.Future<void> updatePlaylist(
    String? playlistId,
    String? token,
    _i3.UpdatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlistId, token, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> changePlaylistVisibility(
    String? playlistId,
    String? token,
    _i3.VisibilityRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePlaylistVisibility, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> inviteUserToPlaylist(
    String? playlistId,
    String? token,
    _i3.InviteUserRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inviteUserToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.PlaylistLicenseResponse> getPlaylistLicense(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistLicense, [playlistId, token]),
            returnValue: _i6.Future<_i3.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_12(
                this,
                Invocation.method(#getPlaylistLicense, [playlistId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistLicenseResponse>);

  @override
  _i6.Future<_i3.PlaylistLicenseResponse> updatePlaylistLicense(
    String? playlistId,
    String? token,
    _i3.PlaylistLicenseRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylistLicense, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i6.Future<_i3.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_12(
                this,
                Invocation.method(#updatePlaylistLicense, [
                  playlistId,
                  token,
                  request,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistLicenseResponse>);

  @override
  _i6.Future<_i3.PlaylistTracksResponse> getPlaylistTracks(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTracks, [playlistId, token]),
            returnValue: _i6.Future<_i3.PlaylistTracksResponse>.value(
              _FakePlaylistTracksResponse_13(
                this,
                Invocation.method(#getPlaylistTracks, [playlistId, token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistTracksResponse>);

  @override
  _i6.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? token,
    _i3.AddTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [
              playlistId,
              trackId,
              token,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> moveTrackInPlaylist(
    String? playlistId,
    String? token,
    _i3.MoveTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveTrackInPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletePlaylist(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId, token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.PlaylistsResponse> getSavedEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedEvents, [token]),
            returnValue: _i6.Future<_i3.PlaylistsResponse>.value(
              _FakePlaylistsResponse_9(
                this,
                Invocation.method(#getSavedEvents, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistsResponse>);

  @override
  _i6.Future<_i3.PlaylistsResponse> getPublicEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicEvents, [token]),
            returnValue: _i6.Future<_i3.PlaylistsResponse>.value(
              _FakePlaylistsResponse_9(
                this,
                Invocation.method(#getPublicEvents, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.PlaylistsResponse>);

  @override
  _i6.Future<_i3.VoteResponse> voteForTrack(
    String? playlistId,
    String? token,
    _i3.VoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteForTrack, [playlistId, token, request]),
            returnValue: _i6.Future<_i3.VoteResponse>.value(
              _FakeVoteResponse_14(
                this,
                Invocation.method(#voteForTrack, [playlistId, token, request]),
              ),
            ),
          )
          as _i6.Future<_i3.VoteResponse>);

  @override
  _i6.Future<_i3.BatchAddResult> addMultipleTracksToPlaylist({
    required String? playlistId,
    required List<String>? trackIds,
    required String? token,
    String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleTracksToPlaylist, [], {
              #playlistId: playlistId,
              #trackIds: trackIds,
              #token: token,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i6.Future<_i3.BatchAddResult>.value(
              _FakeBatchAddResult_15(
                this,
                Invocation.method(#addMultipleTracksToPlaylist, [], {
                  #playlistId: playlistId,
                  #trackIds: trackIds,
                  #token: token,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.BatchAddResult>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getRandomTracks({int? count = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomTracks, [], {#count: count}),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i9.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i9.PlaylistUpdateMessage> get playlistUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playlistUpdateStream),
            returnValue: _i6.Stream<_i9.PlaylistUpdateMessage>.empty(),
          )
          as _i6.Stream<_i9.PlaylistUpdateMessage>);

  @override
  _i6.Stream<Map<String, dynamic>> get rawMessageStream =>
      (super.noSuchMethod(
            Invocation.getter(#rawMessageStream),
            returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i6.Future<void> connectToPlaylist(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPlaylist, [playlistId, token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forceReconnect() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void sendMessage(Map<String, dynamic>? message) => super.noSuchMethod(
    Invocation.method(#sendMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FrontendLoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFrontendLoggingService extends _i1.Mock
    implements _i10.FrontendLoggingService {
  MockFrontendLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> sanitizeMetadata(Map<String, dynamic>? metadata) =>
      (super.noSuchMethod(
            Invocation.method(#sanitizeMetadata, [metadata]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void updateUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#updateUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateCurrentRoute(String? route) => super.noSuchMethod(
    Invocation.method(#updateCurrentRoute, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void logUserAction({
    required _i10.UserActionType? actionType,
    required String? description,
    _i10.LogLevel? level = _i10.LogLevel.info,
    Map<String, dynamic>? metadata,
    String? screenName,
    String? customRoute,
  }) => super.noSuchMethod(
    Invocation.method(#logUserAction, [], {
      #actionType: actionType,
      #description: description,
      #level: level,
      #metadata: metadata,
      #screenName: screenName,
      #customRoute: customRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logNavigation(
    String? from,
    String? to, {
    Map<String, dynamic>? metadata,
  }) => super.noSuchMethod(
    Invocation.method(#logNavigation, [from, to], {#metadata: metadata}),
    returnValueForMissingStub: null,
  );

  @override
  void logButtonClick(
    String? buttonName,
    String? screenName, {
    Map<String, dynamic>? metadata,
  }) => super.noSuchMethod(
    Invocation.method(
      #logButtonClick,
      [buttonName, screenName],
      {#metadata: metadata},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logFormSubmit(
    String? formName,
    String? screenName, {
    bool? success = true,
    Map<String, dynamic>? metadata,
  }) => super.noSuchMethod(
    Invocation.method(
      #logFormSubmit,
      [formName, screenName],
      {#success: success, #metadata: metadata},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logSearch(
    String? query,
    String? screenName, {
    int? resultCount,
    Map<String, dynamic>? metadata,
  }) => super.noSuchMethod(
    Invocation.method(
      #logSearch,
      [query, screenName],
      {#resultCount: resultCount, #metadata: metadata},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MusicPlayerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicPlayerService extends _i1.Mock
    implements _i11.MusicPlayerService {
  MockMusicPlayerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DynamicThemeProvider get themeProvider =>
      (super.noSuchMethod(
            Invocation.getter(#themeProvider),
            returnValue: _FakeDynamicThemeProvider_16(
              this,
              Invocation.getter(#themeProvider),
            ),
          )
          as _i4.DynamicThemeProvider);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  Duration get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeDuration_17(this, Invocation.getter(#position)),
          )
          as Duration);

  @override
  Duration get duration =>
      (super.noSuchMethod(
            Invocation.getter(#duration),
            returnValue: _FakeDuration_17(this, Invocation.getter(#duration)),
          )
          as Duration);

  @override
  List<_i8.PlaylistTrack> get playlist =>
      (super.noSuchMethod(
            Invocation.getter(#playlist),
            returnValue: <_i8.PlaylistTrack>[],
          )
          as List<_i8.PlaylistTrack>);

  @override
  int get currentIndex =>
      (super.noSuchMethod(Invocation.getter(#currentIndex), returnValue: 0)
          as int);

  @override
  bool get isShuffleMode =>
      (super.noSuchMethod(Invocation.getter(#isShuffleMode), returnValue: false)
          as bool);

  @override
  bool get isRepeatMode =>
      (super.noSuchMethod(Invocation.getter(#isRepeatMode), returnValue: false)
          as bool);

  @override
  bool get hasPlaylist =>
      (super.noSuchMethod(Invocation.getter(#hasPlaylist), returnValue: false)
          as bool);

  @override
  bool get hasPreviousTrack =>
      (super.noSuchMethod(
            Invocation.getter(#hasPreviousTrack),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasNextTrack =>
      (super.noSuchMethod(Invocation.getter(#hasNextTrack), returnValue: false)
          as bool);

  @override
  bool get isUsingFullAudio =>
      (super.noSuchMethod(
            Invocation.getter(#isUsingFullAudio),
            returnValue: false,
          )
          as bool);

  @override
  double get playbackSpeed =>
      (super.noSuchMethod(Invocation.getter(#playbackSpeed), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> setPlaylistAndPlay({
    required List<_i8.PlaylistTrack>? playlist,
    required int? startIndex,
    String? playlistId,
    String? authToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaylistAndPlay, [], {
              #playlist: playlist,
              #startIndex: startIndex,
              #playlistId: playlistId,
              #authToken: authToken,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playTrack(_i8.Track? track, String? fallbackUrl) =>
      (super.noSuchMethod(
            Invocation.method(#playTrack, [track, fallbackUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playNext() =>
      (super.noSuchMethod(
            Invocation.method(#playNext, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#playPrevious, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playTrackAtIndex(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#playTrackAtIndex, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void toggleShuffle() => super.noSuchMethod(
    Invocation.method(#toggleShuffle, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleRepeat() => super.noSuchMethod(
    Invocation.method(#toggleRepeat, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> togglePlay() =>
      (super.noSuchMethod(
            Invocation.method(#togglePlay, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPlaybackSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackSpeed, [speed]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearPlaylist() => super.noSuchMethod(
    Invocation.method(#clearPlaylist, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearFailedTracks() => super.noSuchMethod(
    Invocation.method(#clearFailedTracks, []),
    returnValueForMissingStub: null,
  );

  @override
  void updatePlaylist(List<_i8.PlaylistTrack>? updatedPlaylist) =>
      super.noSuchMethod(
        Invocation.method(#updatePlaylist, [updatedPlaylist]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i13.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.SignInOption get signInOption =>
      (super.noSuchMethod(
            Invocation.getter(#signInOption),
            returnValue: _i13.SignInOption.standard,
          )
          as _i13.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#forceCodeForRefreshToken),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Stream<_i13.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i6.Stream<_i13.GoogleSignInAccount?>.empty(),
          )
          as _i6.Stream<_i13.GoogleSignInAccount?>);

  @override
  _i6.Future<_i13.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i6.Future<_i13.GoogleSignInAccount?>.value(),
          )
          as _i6.Future<_i13.GoogleSignInAccount?>);

  @override
  _i6.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i13.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i6.Future<_i13.GoogleSignInAccount?>.value(),
          )
          as _i6.Future<_i13.GoogleSignInAccount?>);

  @override
  _i6.Future<_i13.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<_i13.GoogleSignInAccount?>.value(),
          )
          as _i6.Future<_i13.GoogleSignInAccount?>);

  @override
  _i6.Future<_i13.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<_i13.GoogleSignInAccount?>.value(),
          )
          as _i6.Future<_i13.GoogleSignInAccount?>);

  @override
  _i6.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessScopes,
              [scopes],
              {#accessToken: accessToken},
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
