// Mocks generated by Mockito 5.4.6 from annotations
// in music_room/test/providers/voting_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:music_room/models/api_models.dart' as _i2;
import 'package:music_room/models/music_models.dart' as _i10;
import 'package:music_room/providers/auth_providers.dart' as _i6;
import 'package:music_room/providers/voting_providers.dart' as _i4;
import 'package:music_room/services/api_services.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVoteResponse_0 extends _i1.SmartFake implements _i2.VoteResponse {
  _FakeVoteResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignIn_1 extends _i1.SmartFake implements _i3.GoogleSignIn {
  _FakeGoogleSignIn_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_2 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_3 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendsResponse_4 extends _i1.SmartFake
    implements _i2.FriendsResponse {
  _FakeFriendsResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageResponse_5 extends _i1.SmartFake
    implements _i2.MessageResponse {
  _FakeMessageResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendInvitationsResponse_6 extends _i1.SmartFake
    implements _i2.FriendInvitationsResponse {
  _FakeFriendInvitationsResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileByIdResponse_7 extends _i1.SmartFake
    implements _i2.ProfileByIdResponse {
  _FakeProfileByIdResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponse_8 extends _i1.SmartFake
    implements _i2.ProfileResponse {
  _FakeProfileResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeezerSearchResponse_9 extends _i1.SmartFake
    implements _i2.DeezerSearchResponse {
  _FakeDeezerSearchResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistsResponse_10 extends _i1.SmartFake
    implements _i2.PlaylistsResponse {
  _FakePlaylistsResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistDetailResponse_11 extends _i1.SmartFake
    implements _i2.PlaylistDetailResponse {
  _FakePlaylistDetailResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePlaylistResponse_12 extends _i1.SmartFake
    implements _i2.CreatePlaylistResponse {
  _FakeCreatePlaylistResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistLicenseResponse_13 extends _i1.SmartFake
    implements _i2.PlaylistLicenseResponse {
  _FakePlaylistLicenseResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylistTracksResponse_14 extends _i1.SmartFake
    implements _i2.PlaylistTracksResponse {
  _FakePlaylistTracksResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchAddResult_15 extends _i1.SmartFake
    implements _i2.BatchAddResult {
  _FakeBatchAddResult_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VotingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVotingService extends _i1.Mock implements _i4.VotingService {
  MockVotingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.VoteResponse> voteForTrack({
    required String? playlistId,
    required int? trackIndex,
    required String? token,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#voteForTrack, [], {
              #playlistId: playlistId,
              #trackIndex: trackIndex,
              #token: token,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i5.Future<_i2.VoteResponse>.value(
              _FakeVoteResponse_0(
                this,
                Invocation.method(#voteForTrack, [], {
                  #playlistId: playlistId,
                  #trackIndex: trackIndex,
                  #token: token,
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.VoteResponse>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i6.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get hasValidToken =>
      (super.noSuchMethod(Invocation.getter(#hasValidToken), returnValue: false)
          as bool);

  @override
  _i3.GoogleSignIn get googleSignIn =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignIn),
            returnValue: _FakeGoogleSignIn_1(
              this,
              Invocation.getter(#googleSignIn),
            ),
          )
          as _i3.GoogleSignIn);

  @override
  Map<String, String> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSuccess =>
      (super.noSuchMethod(Invocation.getter(#hasSuccess), returnValue: false)
          as bool);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> resetPasswordWithOtp(
    String? email,
    String? otp,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordWithOtp, [email, otp, newPassword]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendSignupEmailOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signupWithOtp(
    String? username,
    String? email,
    String? password,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [username, email, password, otp]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> googleLogin() =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> handleWebGoogleSignIn(_i3.GoogleSignInAccount? user) =>
      (super.noSuchMethod(
            Invocation.method(#handleWebGoogleSignIn, [user]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> facebookLogin() =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkEmailAvailability(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailability, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void setSuccess(String? message) => super.noSuchMethod(
    Invocation.method(#setSuccess, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<T?> executeAsync<T>(
    _i5.Future<T> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<bool> executeBool(
    _i5.Future<void> Function()? operation, {
    String? successMessage,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeBool,
              [operation],
              {#successMessage: successMessage, #errorMessage: errorMessage},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.AuthResult> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_2(this, Invocation.method(#login, [request])),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> logout(String? token, _i2.LogoutRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResult> facebookLogin(_i2.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLogin, [request]),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_2(
                this,
                Invocation.method(#facebookLogin, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> googleLogin(_i2.SocialLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [request]),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_2(
                this,
                Invocation.method(#googleLogin, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> forgotPassword(_i2.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forgotChangePassword(_i2.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotChangePassword, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendSignupEmailOtp(_i2.EmailOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignupEmailOtp, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResult> signupWithOtp(_i2.SignupWithOtpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOtp, [request]),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_2(
                this,
                Invocation.method(#signupWithOtp, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> facebookLink(
    String? token,
    _i2.SocialLinkRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#facebookLink, [token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> googleLink(String? token, _i2.SocialLinkRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#googleLink, [token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserResponse> getUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [token]),
            returnValue: _i5.Future<_i2.UserResponse>.value(
              _FakeUserResponse_3(this, Invocation.method(#getUser, [token])),
            ),
          )
          as _i5.Future<_i2.UserResponse>);

  @override
  _i5.Future<void> userPasswordChange(
    String? token,
    _i2.PasswordChangeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#userPasswordChange, [token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.FriendsResponse> getFriends(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, [token]),
            returnValue: _i5.Future<_i2.FriendsResponse>.value(
              _FakeFriendsResponse_4(
                this,
                Invocation.method(#getFriends, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.FriendsResponse>);

  @override
  _i5.Future<_i2.MessageResponse> sendFriendRequest(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [userId, token]),
            returnValue: _i5.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_5(
                this,
                Invocation.method(#sendFriendRequest, [userId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageResponse>);

  @override
  _i5.Future<_i2.MessageResponse> acceptFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendRequest, [friendshipId, token]),
            returnValue: _i5.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_5(
                this,
                Invocation.method(#acceptFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageResponse>);

  @override
  _i5.Future<_i2.MessageResponse> rejectFriendRequest(
    String? friendshipId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectFriendRequest, [friendshipId, token]),
            returnValue: _i5.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_5(
                this,
                Invocation.method(#rejectFriendRequest, [friendshipId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageResponse>);

  @override
  _i5.Future<void> removeFriend(String? userId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [userId, token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logActivity(
    String? token,
    _i2.ActivityLogRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logActivity, [token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.FriendInvitationsResponse> getReceivedInvitations(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReceivedInvitations, [token]),
            returnValue: _i5.Future<_i2.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_6(
                this,
                Invocation.method(#getReceivedInvitations, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.FriendInvitationsResponse>);

  @override
  _i5.Future<_i2.FriendInvitationsResponse> getSentInvitations(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSentInvitations, [token]),
            returnValue: _i5.Future<_i2.FriendInvitationsResponse>.value(
              _FakeFriendInvitationsResponse_6(
                this,
                Invocation.method(#getSentInvitations, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.FriendInvitationsResponse>);

  @override
  _i5.Future<Map<String, dynamic>> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.ProfileByIdResponse> getProfileById(
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [userId, token]),
            returnValue: _i5.Future<_i2.ProfileByIdResponse>.value(
              _FakeProfileByIdResponse_7(
                this,
                Invocation.method(#getProfileById, [userId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileByIdResponse>);

  @override
  _i5.Future<_i2.ProfileResponse> getMyProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, [token]),
            returnValue: _i5.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_8(
                this,
                Invocation.method(#getMyProfile, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponse>);

  @override
  _i5.Future<void> updateProfile(String? token, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [token, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ProfileResponse> updateProfileFull(
    String? token,
    _i2.ProfileUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileFull, [token, request]),
            returnValue: _i5.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_8(
                this,
                Invocation.method(#updateProfileFull, [token, request]),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponse>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMusicPreferences(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMusicPreferences, [token]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> deleteAvatar(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ProfileResponse> updateProfileWithFile(
    String? token, {
    String? avatarPath,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFile,
              [token],
              {
                #avatarPath: avatarPath,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i5.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_8(
                this,
                Invocation.method(
                  #updateProfileWithFile,
                  [token],
                  {
                    #avatarPath: avatarPath,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponse>);

  @override
  _i5.Future<_i2.ProfileResponse> updateProfileWithFileWeb(
    String? token, {
    List<int>? avatarBytes,
    String? mimeType,
    String? name,
    String? location,
    String? bio,
    String? phone,
    String? friendInfo,
    List<int>? musicPreferencesIds,
    String? avatarVisibility,
    String? nameVisibility,
    String? locationVisibility,
    String? bioVisibility,
    String? phoneVisibility,
    String? friendInfoVisibility,
    String? musicPreferencesVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfileWithFileWeb,
              [token],
              {
                #avatarBytes: avatarBytes,
                #mimeType: mimeType,
                #name: name,
                #location: location,
                #bio: bio,
                #phone: phone,
                #friendInfo: friendInfo,
                #musicPreferencesIds: musicPreferencesIds,
                #avatarVisibility: avatarVisibility,
                #nameVisibility: nameVisibility,
                #locationVisibility: locationVisibility,
                #bioVisibility: bioVisibility,
                #phoneVisibility: phoneVisibility,
                #friendInfoVisibility: friendInfoVisibility,
                #musicPreferencesVisibility: musicPreferencesVisibility,
              },
            ),
            returnValue: _i5.Future<_i2.ProfileResponse>.value(
              _FakeProfileResponse_8(
                this,
                Invocation.method(
                  #updateProfileWithFileWeb,
                  [token],
                  {
                    #avatarBytes: avatarBytes,
                    #mimeType: mimeType,
                    #name: name,
                    #location: location,
                    #bio: bio,
                    #phone: phone,
                    #friendInfo: friendInfo,
                    #musicPreferencesIds: musicPreferencesIds,
                    #avatarVisibility: avatarVisibility,
                    #nameVisibility: nameVisibility,
                    #locationVisibility: locationVisibility,
                    #bioVisibility: bioVisibility,
                    #phoneVisibility: phoneVisibility,
                    #friendInfoVisibility: friendInfoVisibility,
                    #musicPreferencesVisibility: musicPreferencesVisibility,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponse>);

  @override
  _i5.Future<_i2.DeezerSearchResponse> searchDeezerTracks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDeezerTracks, [query]),
            returnValue: _i5.Future<_i2.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_9(
                this,
                Invocation.method(#searchDeezerTracks, [query]),
              ),
            ),
          )
          as _i5.Future<_i2.DeezerSearchResponse>);

  @override
  _i5.Future<_i2.DeezerSearchResponse> searchTracks(
    String? query,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query, token]),
            returnValue: _i5.Future<_i2.DeezerSearchResponse>.value(
              _FakeDeezerSearchResponse_9(
                this,
                Invocation.method(#searchTracks, [query, token]),
              ),
            ),
          )
          as _i5.Future<_i2.DeezerSearchResponse>);

  @override
  _i5.Future<_i10.Track?> getDeezerTrack(String? trackId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getDeezerTrack, [trackId, token]),
            returnValue: _i5.Future<_i10.Track?>.value(),
          )
          as _i5.Future<_i10.Track?>);

  @override
  _i5.Future<Map<String, dynamic>> addTrackFromDeezer(
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackFromDeezer, [trackId, token]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.PlaylistsResponse> getSavedPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedPlaylists, [token]),
            returnValue: _i5.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_10(
                this,
                Invocation.method(#getSavedPlaylists, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistsResponse>);

  @override
  _i5.Future<_i2.PlaylistsResponse> getPublicPlaylists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicPlaylists, [token]),
            returnValue: _i5.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_10(
                this,
                Invocation.method(#getPublicPlaylists, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistsResponse>);

  @override
  _i5.Future<_i2.PlaylistDetailResponse> getPlaylist(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [id, token]),
            returnValue: _i5.Future<_i2.PlaylistDetailResponse>.value(
              _FakePlaylistDetailResponse_11(
                this,
                Invocation.method(#getPlaylist, [id, token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistDetailResponse>);

  @override
  _i5.Future<_i2.CreatePlaylistResponse> createPlaylist(
    String? token,
    _i2.CreatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [token, request]),
            returnValue: _i5.Future<_i2.CreatePlaylistResponse>.value(
              _FakeCreatePlaylistResponse_12(
                this,
                Invocation.method(#createPlaylist, [token, request]),
              ),
            ),
          )
          as _i5.Future<_i2.CreatePlaylistResponse>);

  @override
  _i5.Future<void> updatePlaylist(
    String? playlistId,
    String? token,
    _i2.UpdatePlaylistRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlistId, token, request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePlaylistVisibility(
    String? playlistId,
    String? token,
    _i2.VisibilityRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePlaylistVisibility, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> inviteUserToPlaylist(
    String? playlistId,
    String? token,
    _i2.InviteUserRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inviteUserToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PlaylistLicenseResponse> getPlaylistLicense(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistLicense, [playlistId, token]),
            returnValue: _i5.Future<_i2.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_13(
                this,
                Invocation.method(#getPlaylistLicense, [playlistId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistLicenseResponse>);

  @override
  _i5.Future<_i2.PlaylistLicenseResponse> updatePlaylistLicense(
    String? playlistId,
    String? token,
    _i2.PlaylistLicenseRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylistLicense, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i5.Future<_i2.PlaylistLicenseResponse>.value(
              _FakePlaylistLicenseResponse_13(
                this,
                Invocation.method(#updatePlaylistLicense, [
                  playlistId,
                  token,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistLicenseResponse>);

  @override
  _i5.Future<_i2.PlaylistTracksResponse> getPlaylistTracks(
    String? playlistId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTracks, [playlistId, token]),
            returnValue: _i5.Future<_i2.PlaylistTracksResponse>.value(
              _FakePlaylistTracksResponse_14(
                this,
                Invocation.method(#getPlaylistTracks, [playlistId, token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistTracksResponse>);

  @override
  _i5.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? token,
    _i2.AddTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [
              playlistId,
              trackId,
              token,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> moveTrackInPlaylist(
    String? playlistId,
    String? token,
    _i2.MoveTrackRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveTrackInPlaylist, [
              playlistId,
              token,
              request,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletePlaylist(String? playlistId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId, token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.PlaylistsResponse> getSavedEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedEvents, [token]),
            returnValue: _i5.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_10(
                this,
                Invocation.method(#getSavedEvents, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistsResponse>);

  @override
  _i5.Future<_i2.PlaylistsResponse> getPublicEvents(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicEvents, [token]),
            returnValue: _i5.Future<_i2.PlaylistsResponse>.value(
              _FakePlaylistsResponse_10(
                this,
                Invocation.method(#getPublicEvents, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.PlaylistsResponse>);

  @override
  _i5.Future<_i2.VoteResponse> voteForTrack(
    String? playlistId,
    String? token,
    _i2.VoteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#voteForTrack, [playlistId, token, request]),
            returnValue: _i5.Future<_i2.VoteResponse>.value(
              _FakeVoteResponse_0(
                this,
                Invocation.method(#voteForTrack, [playlistId, token, request]),
              ),
            ),
          )
          as _i5.Future<_i2.VoteResponse>);

  @override
  _i5.Future<_i2.BatchAddResult> addMultipleTracksToPlaylist({
    required String? playlistId,
    required List<String>? trackIds,
    required String? token,
    String? deviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleTracksToPlaylist, [], {
              #playlistId: playlistId,
              #trackIds: trackIds,
              #token: token,
              #deviceUuid: deviceUuid,
            }),
            returnValue: _i5.Future<_i2.BatchAddResult>.value(
              _FakeBatchAddResult_15(
                this,
                Invocation.method(#addMultipleTracksToPlaylist, [], {
                  #playlistId: playlistId,
                  #trackIds: trackIds,
                  #token: token,
                  #deviceUuid: deviceUuid,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.BatchAddResult>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRandomTracks({int? count = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomTracks, [], {#count: count}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
