# Generated by Django 5.1 on 2025-06-18 05:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimepasscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupOneTimePasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.IntegerField()),
                ('expired_at', models.DateTimeField(default=apps.users.models.get_expiry_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
