# Generated by Django 5.1 on 2025-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_signuponetimepasscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepasscode',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signuponetimepasscode',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
