# Generated by Django 5.1 on 2025-06-21 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='allowed_radius_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_to_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='license_type',
            field=models.CharField(choices=[('open', 'Open to everyone'), ('invite_only', 'Invite only'), ('location_time', 'Time and location restricted')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='vote_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='vote_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
