# Generated by Django 5.1 on 2025-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
