# Generated by Django 5.1 on 2025-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_allowed_radius_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
