# Generated by Django 5.1 on 2025-06-28 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlisttrack_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='users_already_voted',
            field=models.ManyToManyField(blank=True, related_name='already_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
