# Generated by Django 5.1 on 2025-06-27 13:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemusic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileprivate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilepublic',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=6, null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('friend_info', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('music_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='ProfileFriend',
        ),
        migrations.DeleteModel(
            name='ProfileMusic',
        ),
        migrations.DeleteModel(
            name='ProfilePrivate',
        ),
        migrations.DeleteModel(
            name='ProfilePublic',
        ),
    ]
